### ISSUE TITLE
Question about the reported results of Embedrank

### ISSUE THREAD

**Issue by laituan245** [sunyilgdx/SIFRank#1]
Hi.

Thank you for the great work. I have one question that I hope you could help with.

In the [original Embedrank paper](https://arxiv.org/pdf/1801.04470.pdf), the variant EmbedRank d2v achieved an F1-score of 31.51 in the Inspec dataset (with N = 5). But your paper reported that it only achieved an F1-score of 27.20. Why is there such a difference? Did you run the original code of Embedrank and it only gave an F1-score of 27.20?

Thanks.

**Comment by sunyilgdx** [comment]
That's a good question, because I had the same doubts during the experiment.
The original code of EmbedRank doesn't have the Evaluation part, so we implemented EmbedRank ourselves in the same environment of SIFRank.
I think the problem is in calculating the value of R.
According to the method of most papers, the formula is as follows:
**P**=**C**correct/**C**extract
**R**=**C**correct/**C**gold
**F1**=**2PR**/**P**+**R**
In Inspec, there are 500 documents, 4912 gold keyphrases
If N=5, **C**extract=500\*5=2500, **C**gold=4912
so **R**=**P**\*2500/4912（the relationship between P and R is linear）
In the paper of EmbedRank, when N=5,  P=0.4149，so the theoretical value of R should be 0.2112, but the R in this paper is 0.2540
I'm curious, maybe we have a different formula

**Comment by laituan245** [comment]
Thank you for the explanation.
